name: Build and Push Docker Image

on: 
  push:
    branches: ["main"]
    tags:
      - "v*.*.*"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  builds:
    runs-on: portfolio-runner

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Extract metadatao
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: $ {{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver.pattern={{major}}.{{minor}}
            type=sha
            
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1

      - name: Log into the Registry
        uses: docker/login-action@v3
        with: 
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:  
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Update K8 resource

        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            NEW_TAG="${{ github.ref_name }}"
          else
            NEW_TAG="sha-$(git rev-parse --short HEAD)"
          fi

          echo "Updating deployment to use image tag: $NEW_TAG"

          # regex look for image line and replace after colon
          sed -i "s|image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:.*|image ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:$NEW_TAG|" k8/deployment.yaml

          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Check if there are changes to commit (prevent failure if file didn't change)
          if [[ -n $(git status -s k8s/deployment.yaml) ]]; then
            git add k8s/deployment.yaml
            git commit -m "k8s: update deployment image to $NEW_TAG"
            git push origin HEAD:${{ github.ref_name }}
          else
            echo "No changes to deployment.yaml"
          fi
          
          
      
